server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_agentscope?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
  flyway:
    enabled: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
